name: Process JSON File

on:
  pull_request:
    types: [closed]

jobs:
  process_json_file:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract PR body and save as JSON file
        run: |
          echo "${{ github.event.pull_request.body }}" > pr_body.json
          echo "PR body saved to pr_body.json"
          cat pr_body.json  # Adding this to view what's being saved

      - name: Setup Python and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          echo "Python and dependencies installed."

      - name: Process JSON File
        run: python3 update.py pr_body.json

      - name: Commit and Push Processed JSON
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add pr_body.json
          git commit -m "Update processed JSON"
          git push
          echo "Committed and pushed the processed JSON file."

      - name: Upload PR body as an artifact if the process fails
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failed-pr-body
          path: pr_body.json
